### ISSUE TITLE
Decide schemas for various models.

### ISSUE THREAD

**Issue by coditva** [BitsAiims2017/api#16]
Decide and keep all the final schemas in this thread.

**Comment by coditva** [comment]
Item:
- Name
- Price
- Class
- Quantity
- Category
- Remarks

**Comment by coditva** [comment]
User:
- Name
- Username
- Password
- Role (admin, viewer, seller, purchaser)
- Date joined

**Comment by UtkarshMe** [comment]
Orders:
- order_id
- added by
- items (array of json objects)
- total price
- data ordered
- status (fulfilled, pending)

**Comment by UtkarshMe** [comment]
Transactions:
- sold by
- date
- items
- total

**Comment by coditva** [comment]
Patient:
- Name
- ID
- Age (Self increment?)
- Reports (Array)
- Open Consultation (Array)

**Comment by coditva** [comment]
Report:
- ID
- Symptoms
- Diagnosis/tests
- Conclusion
- Remarks
- Diagnosed by (Array)
- Date started
- Date updated
